export const TEACHER_SIGNIN = 'TEACHER_SIGNIN';
export const TEACHER_VERIFIED = 'TEACHER_VERIFIED';
export const TEACHER_SIGNOUT = 'TEACHER_SIGNOUT';

export const GET_DEPARTMENT_REQUEST = 'GET_DEPARTMENT_REQUEST';
export const GET_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS';
export const GET_DEPARTMENT_ERROR = 'GET_DEPARTMENT_ERROR';
