export const TEACHER_SIGNIN = 'TEACHER_SIGNIN';
export const TEACHER_VERIFIED = 'TEACHER_VERIFIED';
export const TEACHER_SIGNOUT = 'TEACHER_SIGNOUT';

export const GET_DEPARTMENT_REQUEST = 'GET_DEPARTMENT_REQUEST';
export const GET_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS';
export const GET_DEPARTMENT_ERROR = 'GET_DEPARTMENT_ERROR';

export const GET_ONE_DEPARTMENT_REQUEST = 'GET_ONE_DEPARTMENT_REQUEST';
export const GET_ONE_DEPARTMENT_SUCCESS = 'GET_ONE_DEPARTMENT_SUCCESS';
export const GET_ONE_DEPARTMENT_ERROR = 'GET_ONE_DEPARTMENT_ERROR';

export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_ERROR = 'GET_STUDENT_ERROR';

export const GET_STUDENT_BY_ID_REQUEST = 'GET_STUDENT_BY_ID_REQUEST';
export const GET_STUDENT_BY_ID_SUCCESS = 'GET_STUDENT_BY_ID_SUCCESS';
export const GET_STUDENT_BY_ID_ERROR = 'GET_STUDENT_BY_ID_ERROR';
